"""
app/superadmin/routes/email_settings.py — Global email config: settings, provider status, diagnostics (Phase 4b, batch 8)

Moved here verbatim from the former monolithic app/superadmin/__init__.py.
No behavior, route, or endpoint-name changes — see blueprint split plan.
"""

import csv
import io
import logging
import re
import secrets
import requests
import string
from datetime import datetime, timezone, timedelta
from functools import wraps

from flask import (
    Blueprint, render_template, redirect, url_for,
    flash, request, session, current_app, Response,
)
from urllib.parse import urlparse
from flask_login import current_user, logout_user, login_required
from pathlib import Path
from sqlalchemy import or_, func
from werkzeug.utils import secure_filename

from app.auth import _handle_login
from app.forms import (
    ChangePasswordForm, SuperadminAccountForm,
    TenantForm, SuperadminMessageForm, PaymentInstructionForm, PaymentMethodForm,
)
from app import db, limiter
from app.repositories import (
    profile_repository,
    tenant_repository,
    user_repository,
    project_repository,
    testimonial_repository,
    inquiry_repository,
    activity_log_repository,
    subscription_repository,
    payment_method_repository,
    payment_submission_repository,
    subscription_notification_repository,
    webhook_event_repository,
    global_email_config_repository,
)
from app.services.manual_billing import (
    approve_payment_submission,
    reject_payment_submission,
    save_billing_upload,
    set_default_payment_method,
)
from app.services.tenant_admin import delete_tenant_completely
from app.utils import is_paymongo_enabled, set_paymongo_enabled
from app.models import User
from app.models.portfolio import (Profile, PaymentMethod, PaymentSubmission, Subscription, WebhookEvent,
                                   ActivityLog, Project, Inquiry, Tenant, PaymentInstruction, PAID_PLAN_NAMES,
                                   normalize_plan_name)


from app.utils import log_activity, BILLING_PLANS, YEARLY_DISCOUNT
from app.security import log_security_event
from app.tenant_security import RESERVED_SLUGS, validate_slug, stamp_session_tenant
from app.models.portfolio import TenantCommunicationSettings
from app.models.portfolio import _utcnow
from app.services.billing import (
    compute_billing_metrics,
    tenant_billing_summary,
    force_activate_subscription,
    sync_subscription_from_paymongo,
)


from app.superadmin.blueprint import superadmin, superadmin_required

logger = logging.getLogger(__name__)


def _email_domain(value: str | None) -> str:
    email = (value or '').strip().lower()
    if '@' not in email:
        return ''
    return email.rsplit('@', 1)[-1]


def _deliverability_checklists(cfg, providers_status: dict) -> dict:
    """Build admin-facing deliverability hints without DNS API calls or secrets."""
    import os

    reply_to = (
        os.environ.get('SUPERADMIN_REPLY_TO_EMAIL', '').strip()
        or os.environ.get('EMAIL_REPLY_TO', '').strip()
        or os.environ.get('REPLY_TO_EMAIL', '').strip()
    )
    platform_domain = 'myportfoliohub.online'

    def item(label: str, ok: bool | None, note: str = '') -> dict:
        return {'label': label, 'ok': ok, 'note': note}

    data: dict[str, dict] = {}

    # MailerSend
    if providers_status.get('mailersend', {}).get('active'):
        sender = (cfg.superadmin_sender_email or cfg.sender_email or '').strip().lower()
        domain = _email_domain(sender)
        data['mailersend'] = {
            'title': 'MailerSend',
            'sender': sender,
            'items': [
                item('Sender email configured', bool(sender), sender or 'Add noreply@myportfoliohub.online or support@myportfoliohub.online.'),
                item('Sender domain matches your verified MailerSend domain', None, 'Confirm this in MailerSend → Domains before production.'),
                item('SPF configured', None, f'Add the MailerSend SPF value shown in your MailerSend dashboard for {domain or platform_domain}.'),
                item('DKIM configured', None, 'Add the DKIM records generated by MailerSend.'),
                item('DMARC configured', None, f'Create a DMARC record for {domain or platform_domain}.'),
                item('From email is provider-approved', None, 'Use a sender approved by MailerSend, such as noreply@myportfoliohub.online or support@myportfoliohub.online.'),
                item('Reply-To configured', bool(reply_to or sender), reply_to or sender or 'Set SUPERADMIN_REPLY_TO_EMAIL / EMAIL_REPLY_TO.'),
                item('Test email sent successfully', None, 'Use the Send Test button after saving.'),
            ],
        }

    # SMTP
    if providers_status.get('smtp', {}).get('active'):
        host = (cfg.sa_smtp_host or '').strip().lower()
        username = (cfg.sa_smtp_username or '').strip().lower()
        sender = (cfg.sa_smtp_sender_email or username or '').strip().lower()
        sender_domain = _email_domain(sender)
        username_domain = _email_domain(username)
        is_gmail = 'gmail.com' in host or username_domain == 'gmail.com'
        sender_matches_user = bool(sender and username and sender == username)
        smtp_send_as_ok = (not is_gmail) or sender_matches_user
        data['smtp'] = {
            'title': 'SMTP / Gmail',
            'sender': sender,
            'items': [
                item('Sender email configured', bool(sender), sender or 'Set Sender Email.'),
                item('Sender domain matches verified domain', None, f'For custom SMTP, verify {sender_domain or platform_domain} with the mailbox/provider if required.'),
                item('SPF configured', None, f'Your SPF should authorize this SMTP provider for {sender_domain or platform_domain}.'),
                item('DKIM configured', None, 'Enable DKIM in your email host when available.'),
                item('DMARC configured', None, f'Create a DMARC record for {sender_domain or platform_domain}.'),
                item('From email matches SMTP username or verified Send As', smtp_send_as_ok, 'Gmail works best when Sender Email equals the SMTP username unless Gmail Send As is verified.'),
                item('SMTP username matches sender email or provider allows Send As', smtp_send_as_ok, 'Sender mismatch may cause spam or rejection.' if not smtp_send_as_ok else username),
                item('Reply-To configured', bool(reply_to or sender), reply_to or sender or 'Set SUPERADMIN_REPLY_TO_EMAIL / EMAIL_REPLY_TO.'),
                item('Test email sent successfully', None, 'Use Test Connection, then Send Test.'),
            ],
        }

    # Resend
    if providers_status.get('resend', {}).get('active'):
        sender = (cfg.sa_resend_sender_email or '').strip().lower()
        domain = _email_domain(sender)
        using_resend_dev = sender.endswith('@resend.dev') or domain == 'resend.dev'
        data['resend'] = {
            'title': 'Resend',
            'sender': sender,
            'items': [
                item('Sender email configured', bool(sender), sender or 'Add noreply@myportfoliohub.online or support@myportfoliohub.online.'),
                item('Sender domain matches your verified Resend domain', False if using_resend_dev else None, 'Do not use onboarding/resend.dev for production.' if using_resend_dev else 'Confirm this in Resend → Domains.'),
                item('SPF configured', None, f'Add the Resend SPF value shown in your Resend dashboard for {domain or platform_domain}.'),
                item('DKIM configured', None, 'Add the DKIM records generated by Resend.'),
                item('DMARC configured', None, f'Create a DMARC record for {domain or platform_domain}.'),
                item('From email is provider-approved', False if using_resend_dev else None, 'Use a verified production-domain sender.' if using_resend_dev else 'Use a sender approved by Resend.'),
                item('Reply-To configured', bool(reply_to or sender), reply_to or sender or 'Set SUPERADMIN_REPLY_TO_EMAIL / EMAIL_REPLY_TO.'),
                item('Test email sent successfully', None, 'Use the Send Test button after saving.'),
            ],
        }
    return data


@superadmin.route('/settings', methods=['GET', 'POST'])
@superadmin_required
def settings():
    account_form  = SuperadminAccountForm(prefix='account')
    password_form = ChangePasswordForm(prefix='password')

    if request.method == 'GET':
        account_form.username.data = current_user.username
        account_form.email.data    = current_user.email

    # Check which form was actually submitted by looking for its prefixed field names
    account_form_submitted = request.method == 'POST' and 'account-username' in request.form
    password_form_submitted = request.method == 'POST' and 'password-current_password' in request.form

    if account_form_submitted and account_form.validate_on_submit():
        if current_user.verify_password(account_form.current_password.data):
            current_user.username = account_form.username.data.strip()
            current_user.email    = account_form.email.data.strip().lower()
            db.session.commit()
            log_activity('update', 'user', current_user.username, 'Superadmin account updated')
            flash('Account details updated successfully!', 'success')
            return redirect(url_for('superadmin.settings'))
        flash('Current password is incorrect.', 'danger')
    elif password_form_submitted and password_form.validate_on_submit():
        if current_user.verify_password(password_form.current_password.data):
            current_user.password = password_form.new_password.data
            db.session.commit()
            log_activity('update', 'user', current_user.username, 'Superadmin password changed')
            flash('Password changed successfully!', 'success')
            return redirect(url_for('superadmin.settings'))
        flash('Current password is incorrect.', 'danger')

    return render_template(
        'superadmin/settings.html',
        account_form=account_form,
        password_form=password_form,
        page_title='Superadmin Settings',
    )

@superadmin.route('/settings/email', methods=['GET', 'POST'])
@superadmin_required
def email_settings():
    """
    Superadmin → Settings → Email & Forms (v5.9.1)

    Multi-provider email configuration for admin/superadmin portal OTP delivery.
    Supports MailerSend, SMTP (Gmail/custom), and Resend with drag-to-reorder
    provider priority and per-provider active toggle.

    AJAX actions (POST with action=...):
      validate_mailersend_key  — validate against MailerSend API
      validate_smtp            — test SMTP connection
      validate_resend          — validate against Resend API
      send_test_email          — send test through active provider chain
      save_priority            — update provider priority order
      toggle_provider          — enable/disable a provider
      save_mailersend          — save MailerSend credentials
      save_smtp                — save SMTP credentials
      save_resend              — save Resend credentials
      save_otp                 — save OTP expiry / recovery settings
    """
    from app.models.core import GlobalEmailConfig
    from app.services.mailersend_service import validate_mailersend_key
    from app.services.superadmin_email_service import send_email as _sa_send
    from flask import jsonify
    import re as _re
    import json as _json

    # Always expire ALL session objects before reading — the identity map
    # can return stale objects from previous requests in the same session,
    # causing has_sa_smtp / has_sa_resend to read outdated column values.
    # Use fresh=True to fully discard the session and re-query from DB.
    cfg = GlobalEmailConfig.get(fresh=True)

    if request.method == 'POST':
        action = request.form.get('action', 'save')

        # ── AJAX: validate MailerSend key ──────────────────────────────────
        # ── AJAX: validate MailerSend key (uses stored key if field blank) ─────────
        if action == 'validate_mailersend_key':
            key = request.form.get('mailersend_api_key', '').strip()
            # If no new key typed, validate the currently stored key
            if not key:
                key = cfg.get_portal_key('superadmin') if cfg else ''
            if not key:
                return jsonify({'ok': False, 'message': 'No MailerSend key configured. Save a key first.'})
            valid, msg = validate_mailersend_key(key)
            return jsonify({'ok': valid, 'message': msg})

        # ── AJAX: send test email (via active provider chain) ──────────────
        if action == 'send_test_email':
            test_to = request.form.get('test_email', '').strip().lower()
            if not test_to or not _re.match(r'^[^\s@]+@[^\s@]+\.[^\s@]{2,}$', test_to):
                return jsonify({'ok': False, 'message': 'Invalid recipient email address.'})
            # Pre-flight: check if any provider is active + configured
            from app.services.superadmin_email_service import _resolve_configs
            active_providers = _resolve_configs()
            if not active_providers:
                return jsonify({'ok': False, 'message': (
                    'No active providers. Configure and toggle at least one provider ON, then retry.'
                )})
            ok, result = _sa_send(
                to=test_to,
                subject='[Portfolio CMS] Email Delivery Test',
                html='<p>This is a <strong>test email</strong> from Portfolio CMS confirming your provider is configured.</p>',
            )
            if ok:
                current_app.logger.info('Test email sent to %s by superadmin %s', test_to, current_user.username)
                return jsonify({'ok': True, 'message': f'Test email delivered to {test_to}.'})
            return jsonify({'ok': False, 'message': f'Delivery failed: {result}'})

        # ── AJAX: validate SMTP (uses stored DB credentials when form fields blank) ──
        if action == 'validate_smtp':
            import smtplib, ssl as _ssl
            # Fall back to stored DB values when form fields are empty
            host     = request.form.get('smtp_host',     '').strip() or (cfg.sa_smtp_host     or '')
            port_raw = request.form.get('smtp_port',     '').strip() or str(cfg.sa_smtp_port  or 587)
            username = request.form.get('smtp_username', '').strip() or (cfg.sa_smtp_username or '')
            enc      = (request.form.get('smtp_encryption', '').strip() or cfg.sa_smtp_encryption or 'tls').lower()

            # Password: prefer form value; fall back to decrypted DB value;
            # if decryption fails but raw blob exists, still allow the test
            # (the actual SMTP send will fail if the key is wrong, not silently pass).
            form_password = request.form.get('smtp_password', '').strip()
            if form_password and ('gmail.com' in host.lower() or username.lower().endswith('@gmail.com')):
                # Google displays 16-character App Passwords in groups. SMTP expects
                # the same value without spaces. Normalizing here prevents a valid
                # pasted App Password from failing authentication in production.
                form_password = ''.join(form_password.split())
            if form_password:
                password = form_password
            else:
                try:
                    password = cfg.sa_smtp_password or ''
                except Exception:
                    password = ''
                # If decryption returned empty but blob exists, we still have credentials
                # stored — we just can't decrypt them (Fernet key mismatch).
                if not password:
                    raw_blob = cfg.get_sa_smtp_password_blob()
                    if raw_blob:
                        return jsonify({'ok': False, 'message': (
                            'Stored SMTP password cannot be decrypted — the FERNET_KEY may have changed. '
                            'Re-enter and save your SMTP password to fix this.'
                        )})

            if not host:
                return jsonify({'ok': False, 'message': 'SMTP host not set. Save your SMTP settings first.'})
            if not username:
                return jsonify({'ok': False, 'message': 'SMTP username not set.'})
            if not password:
                return jsonify({'ok': False, 'message': 'SMTP password not set. Enter your App Password above or save SMTP settings first.'})
            try:
                port = max(1, min(65535, int(port_raw)))
            except (ValueError, TypeError):
                port = 587
            try:
                if enc == 'ssl' or port == 465:
                    ctx = _ssl.create_default_context()
                    with smtplib.SMTP_SSL(host, port, context=ctx, timeout=15) as s:
                        s.login(username, password)
                elif enc == 'none':
                    with smtplib.SMTP(host, port, timeout=15) as s:
                        s.login(username, password)
                else:  # tls (STARTTLS)
                    with smtplib.SMTP(host, port, timeout=15) as s:
                        s.ehlo()
                        s.starttls(context=_ssl.create_default_context())
                        s.ehlo()
                        s.login(username, password)
                return jsonify({'ok': True, 'message': f'✓ SMTP connection to {host}:{port} successful. Authentication passed.'})
            except smtplib.SMTPAuthenticationError:
                hint = ' For Gmail, use an App Password (not your account password).' if 'gmail' in host.lower() else ''
                return jsonify({'ok': False, 'message': f'Authentication failed — check your username and password.{hint}'})
            except (TimeoutError, OSError):
                if host.lower() == 'smtp.gmail.com' and port == 587 and enc != 'ssl':
                    try:
                        with smtplib.SMTP_SSL(host, 465, context=_ssl.create_default_context(), timeout=15) as s:
                            s.login(username, password)
                        return jsonify({
                            'ok': True,
                            'message': '✓ Gmail authenticated through SSL port 465 because this server blocks STARTTLS port 587. Change Port to 465 and Encryption to SSL, then Save SMTP.',
                            'suggested_port': 465,
                            'suggested_encryption': 'ssl',
                        })
                    except smtplib.SMTPAuthenticationError:
                        return jsonify({'ok': False, 'message': 'Gmail was reached on SSL port 465, but authentication failed. Use a 16-character Google App Password, not your normal password.'})
                    except (TimeoutError, OSError):
                        return jsonify({'ok': False, 'message': 'This hosting server blocks Gmail SMTP on both ports 587 and 465. Your password was not tested. Configure Resend or MailerSend (HTTPS) or ask the host to allow outbound SMTP.'})
                return jsonify({'ok': False, 'message': f'Connection to {host}:{port} timed out or was refused before authentication. The password was not tested; check your hosting provider\'s outbound SMTP policy.'})
            except smtplib.SMTPConnectError as e:
                return jsonify({'ok': False, 'message': f'Could not connect to {host}:{port}. Verify the host is correct.'})
            except Exception as e:
                safe = str(e)[:120].replace(password, '***') if password else str(e)[:120]
                return jsonify({'ok': False, 'message': f'Connection failed: {safe}'})

        # ── AJAX: validate Resend (uses stored DB key when form field blank) ──────
        if action == 'validate_resend':
            key = request.form.get(
                'resend_api_key',
                ''
            ).strip() or cfg.sa_resend_api_key

            if not key:
                return jsonify({
                    'ok': False,
                    'message': 'No Resend API key configured.'
                })

            try:
                response = requests.get(
                    'https://api.resend.com/domains',
                    headers={
                        'Authorization': f'Bearer {key}',
                        'Content-Type': 'application/json',
                    },
                    timeout=15
                )

                if response.status_code == 200:
                    return jsonify({
                        'ok': True,
                        'message': 'Resend API key verified successfully.'
                    })

                if response.status_code == 401:
                    return jsonify({
                        'ok': False,
                        'message': 'Invalid Resend API key.'
                    })

                return jsonify({
                    'ok': False,
                    'message': f'Resend returned HTTP {response.status_code}'
                })

            except Exception as e:
                return jsonify({
                    'ok': False,
                    'message': str(e)
                })
        # ── AJAX: save provider priority order ─────────────────────────────
        if action == 'save_priority':
            order_raw = request.form.get('priority_order', '').strip()
            try:
                order = _json.loads(order_raw)
                from app.services.email.constants import VALID_EMAIL_PROVIDERS
                if not isinstance(order, list):
                    return jsonify({'ok': False, 'message': 'Priority must be a JSON list.'})

                valid_set = set(VALID_EMAIL_PROVIDERS)
                seen = set()
                cleaned = []
                for p in order:
                    pname = str(p).strip()
                    if pname in valid_set and pname not in seen:
                        cleaned.append(pname)
                        seen.add(pname)

                # Reject if client submitted invalid or duplicate entries
                if len(cleaned) != len(order):
                    return jsonify({'ok': False, 'message': 'Priority contains invalid or duplicate providers.'})

                # Must not be empty
                if not cleaned:
                    return jsonify({'ok': False, 'message': 'Priority must contain at least one provider.'})

                cfg.set_sa_provider_priority(cleaned)
                cfg.updated_by = current_user.username
                db.session.commit()
                db.session.expire_all()
                return jsonify({'ok': True, 'message': 'Priority saved.'})
            except Exception as e:
                return jsonify({'ok': False, 'message': str(e)[:160]})

        # ── AJAX: toggle a provider on/off ─────────────────────────────────
        if action == 'toggle_provider':
            provider = request.form.get('provider', '')
            active   = request.form.get('active') == '1'
            if provider == 'mailersend':
                cfg.sa_mailersend_active = active
            elif provider == 'smtp':
                cfg.sa_smtp_active = active
            elif provider == 'resend':
                cfg.sa_resend_active = active
            else:
                return jsonify({'ok': False, 'message': 'Unknown provider.'})
            cfg.updated_by = current_user.username
            db.session.commit()
            db.session.expire_all()
            return jsonify({'ok': True, 'message': f'{provider} {"enabled" if active else "disabled"}.'})

        # ── Save MailerSend credentials ────────────────────────────────────
        if action == 'save_mailersend':
            import logging as _log_ms
            _ms_log = _log_ms.getLogger('superadmin.mailersend_save')

            key          = request.form.get('mailersend_api_key', '').strip()
            sender_name  = request.form.get('mailersend_sender_name', '').strip()
            sender_email = request.form.get('mailersend_sender_email', '').strip().lower()

            # Require at least a key OR an existing encrypted key already stored
            existing_blob = getattr(cfg, '_superadmin_mailersend_api_key', '') or ''
            has_existing  = isinstance(existing_blob, str) and len(existing_blob.strip()) > 0

            if not key and not has_existing:
                return jsonify({'ok': False, 'message': 'MailerSend API key is required on first save.'})

            if key:
                cfg.superadmin_mailersend_api_key = key
                # Verify encryption ran
                blob_after = getattr(cfg, '_superadmin_mailersend_api_key', '') or ''
                if not str(blob_after).strip():
                    _ms_log.error('[MS SAVE] Encryption failure — blob empty after setter')
                    db.session.rollback()
                    return jsonify({'ok': False, 'message': 'MailerSend key encryption failed. Check FERNET_KEY.'})

            if sender_name:
                cfg.superadmin_sender_name = sender_name
            if sender_email:
                cfg.superadmin_sender_email = sender_email
            cfg.updated_by = current_user.username

            _ms_log.info('[MS SAVE] Committing (user=%s)', current_user.username)
            db.session.commit()

            # Fresh-read verification — bypass identity map
            config_id = cfg.id
            db.session.remove()
            v = global_email_config_repository.get_fresh_by_id(config_id)
            configured = bool(v.has_superadmin_mailersend or v.has_mailersend) if v else False
            _ms_log.info('[MS SAVE] Verified — configured=%s (user=%s)', configured, current_user.username)

            return jsonify({
                'ok': True,
                'message': 'MailerSend settings saved.',
                'providers': {
                    'mailersend': {
                        'configured': configured,
                        'active': bool(v.sa_mailersend_active if v and v.sa_mailersend_active is not None else True),
                    },
                },
            })

        # ── Save SMTP credentials (AJAX — returns JSON) ────────────────────
        if action == 'save_smtp':
            import logging as _log_smtp
            _smtp_log = _log_smtp.getLogger('superadmin.smtp_save')

            host         = request.form.get('smtp_host', '').strip()
            port_raw     = request.form.get('smtp_port', '587').strip()
            username     = request.form.get('smtp_username', '').strip()
            password     = request.form.get('smtp_password', '').strip()
            sender_email = request.form.get('smtp_sender_email', '').strip().lower()
            if password and ('gmail.com' in host.lower() or username.lower().endswith('@gmail.com')):
                password = ''.join(password.split())
            sender_name  = request.form.get('smtp_sender_name', '').strip()
            encryption   = request.form.get('smtp_encryption', 'tls').strip().lower()
            if encryption not in {'tls', 'ssl', 'none'}:
                encryption = 'tls'
            try:
                port = max(1, min(65535, int(port_raw)))
            except (ValueError, TypeError):
                port = 587

            # Check if a password is already stored by reading the raw encrypted
            # column directly — never go through decrypt_secret here because a
            # decryption failure (wrong FERNET_KEY, ORM state) returns '' and
            # silently makes us think no password exists.
            existing_pw_blob = cfg.get_sa_smtp_password_blob()
            has_existing_pw  = bool(existing_pw_blob)

            missing = []
            if not host:
                missing.append('SMTP Host')
            if not username:
                missing.append('Username / Email')
            if not sender_email:
                missing.append('Sender Email')
            if not password and not has_existing_pw:
                missing.append('Password / App Password (required on first save)')
            if missing:
                _smtp_log.warning(
                    '[SMTP SAVE] Rejected — missing fields: %s (user=%s)',
                    missing, current_user.username
                )
                return jsonify({'ok': False, 'message': f'SMTP not saved — missing: {", ".join(missing)}.'})

            # ── Phase 1: Write all fields ──────────────────────────────────
            cfg.sa_smtp_host         = host
            cfg.sa_smtp_username     = username
            if password:                          # blank = keep existing encrypted blob
                cfg.sa_smtp_password = password
                # ── Phase 2: Verify encryption actually ran ─────────────
                blob_after_set = cfg.get_sa_smtp_password_blob()
                if not blob_after_set:
                    _smtp_log.error(
                        '[SMTP SAVE] Encryption failure — _sa_smtp_password empty after setter '
                        '(host=%s user=%s)', host, username
                    )
                    db.session.rollback()
                    return jsonify({'ok': False, 'message': (
                        'SMTP password encryption failed. '
                        'Check FERNET_KEY configuration and try again.'
                    )})

            cfg.sa_smtp_sender_email = sender_email or cfg.sa_smtp_sender_email
            cfg.sa_smtp_sender_name  = sender_name or cfg.sa_smtp_sender_name
            cfg.sa_smtp_port         = port
            cfg.sa_smtp_encryption   = encryption
            # Always enable SMTP when saving credentials — user is actively
            # configuring it and expects it to be active immediately.
            cfg.sa_smtp_active       = True
            cfg.updated_by           = current_user.username

            _smtp_log.info(
                '[SMTP SAVE] Committing — host=%s port=%d user=%s sender=%s enc=%s (user=%s)',
                host, port, username, sender_email or '(keep)', encryption, current_user.username
            )

            db.session.commit()

            # ── Phase 3: Fresh-read verification ──────────────────────────
            # Discard session entirely, re-fetch from DB, verify persistence.
            # This is the critical step that prevents stale ORM cache from
            # returning a false 'not configured' state on the next status poll.
            config_id = cfg.id
            db.session.remove()
            verified_cfg = global_email_config_repository.get_fresh_by_id(config_id)

            if verified_cfg is None:
                _smtp_log.error('[SMTP SAVE] Post-commit read returned None — DB integrity issue')
                return jsonify({'ok': False, 'message': 'Save appeared to succeed but verification read failed. Contact support.'})

            # ── Phase 4: Verify encrypted blob persisted ──────────────────
            db_blob = verified_cfg.get_sa_smtp_password_blob()
            if not db_blob:
                _smtp_log.error(
                    '[SMTP SAVE] Post-commit verification failed — sa_smtp_password_encrypted '
                    'is empty in DB after commit (host=%s user=%s)', host, username
                )
                return jsonify({'ok': False, 'message': (
                    'SMTP password did not persist to database. '
                    'This may indicate a FERNET_KEY or DB transaction issue.'
                )})

            configured = bool(verified_cfg.has_sa_smtp)
            _smtp_log.info(
                '[SMTP SAVE] Verified — has_sa_smtp=%s active=%s (user=%s)',
                configured, verified_cfg.sa_smtp_active, current_user.username
            )

            return jsonify({
                'ok': True,
                'message': 'SMTP settings saved and verified.',
                'providers': {
                    'smtp': {
                        'configured': configured,
                        'active': bool(verified_cfg.sa_smtp_active or False),
                    },
                },
            })

        # ── Save Resend credentials ────────────────────────────────────────
        if action == 'save_resend':
            import logging as _log_rs
            _rs_log = _log_rs.getLogger('superadmin.resend_save')

            key          = request.form.get('resend_api_key', '').strip()
            sender_email = request.form.get('resend_sender_email', '').strip().lower()
            sender_name  = request.form.get('resend_sender_name', '').strip()

            existing_blob = cfg.get_sa_resend_api_key_blob()
            has_existing  = bool(existing_blob)

            if not key and not has_existing:
                return jsonify({'ok': False, 'message': 'Resend API key is required on first save.'})

            if key:
                cfg.sa_resend_api_key = key
                blob_after = cfg.get_sa_resend_api_key_blob()
                if not blob_after:
                    _rs_log.error('[RS SAVE] Encryption failure — blob empty after setter')
                    db.session.rollback()
                    return jsonify({'ok': False, 'message': 'Resend key encryption failed. Check FERNET_KEY.'})

            if sender_email:
                cfg.sa_resend_sender_email = sender_email
            cfg.sa_resend_sender_name = sender_name or cfg.sa_resend_sender_name
            # A deliberate credential save should make the provider available
            # to the priority chain, matching SMTP save behaviour.
            cfg.sa_resend_active = True
            cfg.updated_by = current_user.username

            _rs_log.info('[RS SAVE] Committing (user=%s)', current_user.username)
            db.session.commit()

            config_id = cfg.id
            db.session.remove()
            v = global_email_config_repository.get_fresh_by_id(config_id)
            configured = bool(v.has_sa_resend) if v else False
            _rs_log.info('[RS SAVE] Verified — configured=%s (user=%s)', configured, current_user.username)

            return jsonify({
                'ok': True,
                'message': 'Resend settings saved.',
                'providers': {
                    'resend': {
                        'configured': configured,
                        'active': bool(v.sa_resend_effectively_active) if v else False,
                    },
                },
            })

        # ── Save OTP / recovery settings ──────────────────────────────────
        if action == 'save_otp':
            otp_ttl_raw = request.form.get('otp_expiry_minutes', '10').strip()
            recovery_on = request.form.get('recovery_enabled') == 'on'
            try:
                otp_ttl = max(1, min(60, int(otp_ttl_raw)))
            except (ValueError, TypeError):
                otp_ttl = 10
            cfg.otp_expiry_minutes = otp_ttl
            cfg.recovery_enabled   = recovery_on
            cfg.updated_by         = current_user.username
            db.session.commit()
            return jsonify({'ok': True, 'message': f'OTP settings saved. Expiry: {otp_ttl} min, Recovery: {"on" if recovery_on else "off"}.'})

    # ── GET ────────────────────────────────────────────────────────────────
    priority = cfg.get_sa_provider_priority()
    providers_status = {
        'mailersend': {
            'configured': cfg.has_superadmin_mailersend or cfg.has_mailersend,
            'active': cfg.sa_mailersend_active if cfg.sa_mailersend_active is not None else True,
        },
        'smtp': {
            'configured': cfg.has_sa_smtp,
            'active': cfg.sa_smtp_active or False,
        },
        'resend': {
            'configured': cfg.has_sa_resend,
            'active': cfg.sa_resend_effectively_active,
        },
    }
    return render_template(
        'superadmin/email_settings.html',
        cfg=cfg,
        priority=priority,
        providers_status=providers_status,
        deliverability_checklists=_deliverability_checklists(cfg, providers_status),
        has_mailersend=cfg.has_mailersend,
        has_superadmin_mailersend=cfg.has_superadmin_mailersend,
    )

@superadmin.route('/settings/email/provider-status')
@superadmin_required
def email_provider_status():
    """AJAX: return real-time provider configured+active status (v6.6).

    Called by the email settings page on load and after every save/validate
    so badges always reflect the actual backend state.

    Uses GlobalEmailConfig.get(fresh=True) which removes the current session
    and issues a SELECT with populate_existing=True — this guarantees we read
    the committed DB state, never a stale identity-map cache object.
    """
    from app.models.core import GlobalEmailConfig
    from flask import jsonify
    # Force a fresh DB read — expire_all() alone is not enough because
    # db.session.get() still returns the same ORM object from the identity
    # map (just marking it expired and lazy-loading on first attribute
    # access from the same connection's view).  .get(fresh=True) calls
    # db.session.remove() + populate_existing query, bypassing the cache.
    cfg = GlobalEmailConfig.get(fresh=True)
    return jsonify({
        'ok': True,
        'providers': {
            'mailersend': {
                'configured': bool(cfg.has_superadmin_mailersend or cfg.has_mailersend),
                'active': bool(cfg.sa_mailersend_active if cfg.sa_mailersend_active is not None else True),
            },
            'smtp': {
                'configured': bool(cfg.has_sa_smtp),
                'active': bool(cfg.sa_smtp_active or False),
            },
            'resend': {
                'configured': bool(cfg.has_sa_resend),
                'active': bool(cfg.sa_resend_effectively_active),
            },
        },
        'priority': cfg.get_sa_provider_priority(),
    })

@superadmin.route('/settings/email/diagnostics')
@superadmin_required
def email_provider_diagnostics():
    """AJAX: return detailed backend state for debugging SMTP desync issues.

    Returns the raw configuration state without exposing secret values.
    Useful during development and support — can be removed in prod by setting
    EMAIL_DIAGNOSTICS_DISABLED=1 in the environment.
    """
    import os as _os_diag
    from app.models.core import GlobalEmailConfig, decrypt_secret
    from flask import jsonify

    if _os_diag.environ.get('EMAIL_DIAGNOSTICS_DISABLED', '').strip() == '1':
        return jsonify({'ok': False, 'message': 'Diagnostics disabled in this environment.'}), 403

    cfg = GlobalEmailConfig.get(fresh=True)

    # Test decryptability without exposing either secret value.
    smtp_decryptable = False
    smtp_decrypt_error = None
    raw_blob = cfg.get_sa_smtp_password_blob()
    if raw_blob:
        try:
            decrypted = decrypt_secret(raw_blob)
            smtp_decryptable = bool(decrypted)
        except Exception as e:
            smtp_decrypt_error = type(e).__name__

    fernet_key_set = bool(_os_diag.environ.get('FERNET_KEY', '').strip())

    resend_blob = cfg.get_sa_resend_api_key_blob()
    resend_decryptable = False
    resend_decrypt_error = None
    if resend_blob:
        try:
            resend_decryptable = bool(decrypt_secret(resend_blob))
        except Exception as exc:
            resend_decrypt_error = type(exc).__name__

    return jsonify({
        'ok': True,
        'smtp': {
            'host': cfg.sa_smtp_host or '',
            'port': cfg.sa_smtp_port,
            'username': cfg.sa_smtp_username or '',
            'sender_email': cfg.sa_smtp_sender_email or '',
            'encryption': cfg.sa_smtp_encryption or 'tls',
            'active': bool(cfg.sa_smtp_active),
            'encrypted_password_blob_exists': bool(str(raw_blob).strip()),
            'encrypted_password_decryptable': smtp_decryptable,
            'decrypt_error': smtp_decrypt_error,
            'has_sa_smtp': bool(cfg.has_sa_smtp),
        },
        'resend': {
            'sender_email': cfg.sa_resend_sender_email or '',
            'sender_name': cfg.sa_resend_sender_name or '',
            'active': bool(cfg.sa_resend_effectively_active),
            'env_configured': bool(cfg.sa_resend_env_configured),
            'encrypted_key_blob_exists': bool(resend_blob),
            'encrypted_key_decryptable': resend_decryptable,
            'decrypt_error': resend_decrypt_error,
            'has_sa_resend': bool(cfg.has_sa_resend),
        },
        'fernet_key_set': fernet_key_set,
        'priority': cfg.get_sa_provider_priority(),
    })
