"""
app/superadmin/themes.py — SuperAdmin Theme Catalog Management (v6.5)

Routes on the existing `superadmin` blueprint:

  GET            /superadmin/themes                       — catalog list
  POST           /superadmin/themes/sync                  — sync filesystem
  GET/POST       /superadmin/themes/new                   — create entry (no fs theme required)
  GET/POST       /superadmin/themes/<id>/edit             — full editor
  POST           /superadmin/themes/<id>/toggle-active    — activate / deactivate
  POST           /superadmin/themes/<id>/toggle-featured  — featured spotlight
  POST           /superadmin/themes/<id>/upload-thumbnail — thumbnail image upload
  POST           /superadmin/themes/<id>/clear-thumbnail  — clear thumbnail reference
  POST           /superadmin/themes/<id>/upload-banner    — banner image upload
  POST           /superadmin/themes/<id>/clear-banner     — clear banner reference
  POST           /superadmin/themes/<id>/upload-preview   — add screenshot
  POST           /superadmin/themes/<id>/delete-preview   — remove screenshot
  POST           /superadmin/themes/<id>/delete           — remove catalog row
  GET            /superadmin/themes/analytics             — install analytics JSON

No existing routes, models, or the theme engine are modified beyond adding
catalog rows and reading the new extended columns added by migration 0035.
"""

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from flask import (
    abort, current_app, flash, jsonify, redirect,
    render_template, request, url_for,
)

from app import db, limiter
from app.superadmin import superadmin, superadmin_required
from app.theme_engine import (
    get_theme_engine, SUPPORTED_THEME_IDS, is_supported_theme_id,
)
from app.models.core import ThemeCatalogEntry, VALID_REQUIRED_PLANS
from app.utils import log_activity

logger = logging.getLogger(__name__)

# ── Image upload config ───────────────────────────────────────────────────────

_ALLOWED_EXTS   = {'png', 'jpg', 'jpeg', 'webp', 'gif'}
_MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5 MB
_MAX_PREVIEWS   = 6                  # max screenshots per theme


def _allowed_image(filename: str) -> bool:
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in _ALLOWED_EXTS


def _theme_upload_dir() -> Path:
    """Return (and create) the upload directory for theme images."""
    from app.services.media.upload_storage import ensure_upload_folder
    return ensure_upload_folder('themes')




def _normalize_theme_media_url(value: str) -> tuple[str | None, str | None]:
    """Accept only safe image URL values for theme catalog media fields.

    SuperAdmin may paste an external HTTPS/HTTP image URL or use a local
    uploaded `/uploads/...` or legacy `/static/...` path generated by this module. Rejecting every other
    scheme avoids accidentally persisting javascript:, data:, protocol-relative,
    or path-traversal values into public image attributes.
    """
    raw = (value or '').strip()
    if not raw:
        return None, None
    lower = raw.lower()
    if raw.startswith(('/static/', '/uploads/')):
        if '..' in raw or '\\' in raw:
            return None, 'Media path cannot contain traversal segments.'
        return raw, None
    if lower.startswith(('http://', 'https://')):
        return raw, None
    return None, 'Use a full https:// image URL or upload an image from this page.'

def _save_uploaded_image(file_storage, prefix: str) -> str | None:
    """Validate, optimize, and save a theme image through the active provider."""
    if not file_storage or not file_storage.filename:
        return None
    if not _allowed_image(file_storage.filename):
        return None
    # The shared helper performs MIME/magic/Pillow validation, converts to
    # WebP, and uploads to Cloudinary/Supabase/local storage as configured.
    from app.utils import save_image
    url, error = save_image(file_storage, 'themes')
    if not url:
        logger.warning('Theme image upload failed prefix=%s error=%s', prefix, error)
    return url


# ── Theme list ────────────────────────────────────────────────────────────────

@superadmin.route('/themes')
@superadmin_required
def theme_catalog():
    engine = get_theme_engine()
    themes = engine.get_all_themes(include_inactive=True)
    # Sort: featured first, then sort_order, then name
    themes.sort(key=lambda t: (
        not t.get('is_featured', False),
        t.get('sort_order', 0),
        (t.get('name') or t.get('id') or '').lower(),
    ))
    # Analytics summary
    total_installs = sum(t.get('install_count', 0) for t in themes)
    most_popular = max(themes, key=lambda t: t.get('install_count', 0), default=None)
    return render_template(
        'superadmin/themes.html',
        themes=themes,
        page_title='Theme Catalog',
        total_installs=total_installs,
        most_popular=most_popular,
    )


# ── Sync from disk ────────────────────────────────────────────────────────────

@superadmin.route('/themes/sync', methods=['POST'])
@superadmin_required
def theme_catalog_sync():
    from sqlalchemy.exc import OperationalError

    engine = get_theme_engine()

    def _run_sync():
        """Sync the curated filesystem set and remove retired catalog rows.

        Returns ``(created, removed, normalized_profiles)``. OperationalError
        is re-raised so the existing schema-repair path can retry safely.
        """
        created = 0
        removed = 0
        normalized_profiles = 0

        installed = set(SUPPORTED_THEME_IDS)
        for entry in ThemeCatalogEntry.query.all():
            if (entry.slug or '').strip().lower() not in installed:
                db.session.delete(entry)
                removed += 1

        from app.models.tenant_data import Profile
        for profile in Profile.query.filter(
            db.or_(
                Profile.selected_theme.is_(None),
                ~Profile.selected_theme.in_(tuple(installed)),
            )
        ).all():
            profile.selected_theme = 'default'
            db.session.add(profile)
            normalized_profiles += 1

        for meta in engine.registry.all(include_inactive=True):
            slug = meta.get('id')
            if not slug or not is_supported_theme_id(slug) or ThemeCatalogEntry.get_by_slug(slug):
                continue
            entry = ThemeCatalogEntry(
                slug=slug,
                name=meta.get('name') or slug,
                description=meta.get('description') or '',
                category=(meta.get('tags') or [None])[0],
                is_active=True,
                is_premium=bool(meta.get('premium', False)),
                required_plan=meta.get('required_plan') or None,
                sort_order=SUPPORTED_THEME_IDS.index(slug),
            )
            db.session.add(entry)
            created += 1
        return created, removed, normalized_profiles

    try:
        created, removed, normalized_profiles = _run_sync()
    except OperationalError as exc:
        # Schema mismatch (e.g. migration 0035 not yet applied) — this is the
        # exact failure this route used to crash on. Roll back the half-built
        # session, self-repair the schema once, and retry a single time.
        db.session.rollback()
        logger.warning('Theme catalog sync hit a schema mismatch, attempting self-repair: %s', exc)
        try:
            from app import _ensure_theme_catalog_columns
            _ensure_theme_catalog_columns()
            created, removed, normalized_profiles = _run_sync()
            flash('Database schema mismatch detected and repaired.', 'warning')
        except Exception:
            logger.exception('Theme catalog sync: self-repair failed, schema mismatch persists')
            flash('Theme system requires administrator migration review.', 'danger')
            return redirect(url_for('superadmin.theme_catalog'))
    except Exception as exc:
        db.session.rollback()
        logger.exception('Theme catalog sync failed: %s', exc)
        flash('Database error while syncing themes.', 'danger')
        return redirect(url_for('superadmin.theme_catalog'))

    if created or removed or normalized_profiles:
        try:
            db.session.commit()
        except Exception as exc:
            db.session.rollback()
            logger.exception('Theme catalog sync failed: %s', exc)
            flash('Database error while syncing themes.', 'danger')
            return redirect(url_for('superadmin.theme_catalog'))
        engine.clear_cache()
        log_activity(
            'update', 'theme_catalog', 'sync',
            f'Curated themes: created={created}, removed={removed}, profiles_reset={normalized_profiles}',
        )
        flash(
            f'Theme catalog synchronized: {created} added, {removed} retired, '
            f'{normalized_profiles} portfolio selection(s) reset.',
            'success',
        )
    else:
        flash('Theme catalog already matches the curated four-theme set.', 'info')
    return redirect(url_for('superadmin.theme_catalog'))


# ── Analytics JSON ────────────────────────────────────────────────────────────

@superadmin.route('/themes/analytics')
@superadmin_required
def theme_analytics():
    entries = (
        ThemeCatalogEntry.query
        .filter(ThemeCatalogEntry.slug.in_(tuple(SUPPORTED_THEME_IDS)))
        .order_by(ThemeCatalogEntry.install_count.desc())
        .all()
    )
    data = [
        {
            'slug': e.slug,
            'name': e.name or e.slug,
            'install_count': e.install_count or 0,
            'is_featured': bool(e.is_featured),
            'is_active': bool(e.is_active),
        }
        for e in entries
    ]
    return jsonify({'ok': True, 'themes': data})



# ── Create new catalog entry ──────────────────────────────────────────────────

@superadmin.route('/themes/new', methods=['GET', 'POST'])
@superadmin_required
def theme_catalog_new():
    """
    Create a standalone catalog entry for a theme that already exists on disk.
    Useful for registering a theme that the auto-sync missed, or for pre-populating
    metadata before the filesystem theme is deployed.
    """
    if request.method == 'POST':
        slug = (request.form.get('slug') or '').strip().lower()
        name = (request.form.get('name') or '').strip()

        if not slug:
            flash('Slug is required.', 'danger')
            return render_template('superadmin/theme_new.html', page_title='New Theme Entry')

        # Validate slug against the same whitelist the theme engine uses
        from app.theme_engine import is_valid_theme_id
        if not is_valid_theme_id(slug):
            flash('Invalid slug — use only letters, numbers, hyphens, underscores.', 'danger')
            return render_template('superadmin/theme_new.html', page_title='New Theme Entry')
        if not is_supported_theme_id(slug):
            flash('Only the curated production themes can be registered.', 'warning')
            return redirect(url_for('superadmin.theme_catalog'))

        if ThemeCatalogEntry.get_by_slug(slug):
            flash(f'A catalog entry for "{slug}" already exists.', 'warning')
            return redirect(url_for('superadmin.theme_catalog'))

        entry = ThemeCatalogEntry(
            slug=slug,
            name=name or slug,
            is_active=True,
            is_premium=False,
            sort_order=0,
        )
        db.session.add(entry)
        try:
            db.session.commit()
        except Exception as exc:
            db.session.rollback()
            logger.exception('Failed to create theme catalog entry slug=%s: %s', slug, exc)
            flash('Database error while creating entry. Please try again.', 'danger')
            return render_template('superadmin/theme_new.html', page_title='New Theme Entry')

        get_theme_engine().clear_cache()
        log_activity('create', 'theme_catalog', slug, f'Created new catalog entry "{slug}"')
        flash(f'Theme entry "{slug}" created. You can now edit its metadata.', 'success')
        return redirect(url_for('superadmin.theme_catalog_edit', entry_id=entry.id))

    return render_template('superadmin/theme_new.html', page_title='New Theme Entry')


# ── Full editor (GET/POST) ────────────────────────────────────────────────────

def _get_entry_or_404(entry_id):
    entry = db.session.get(ThemeCatalogEntry, entry_id)
    if entry is None:
        abort(404)
    return entry


@superadmin.route('/themes/<int:entry_id>/edit', methods=['GET', 'POST'])
@superadmin_required
def theme_catalog_edit(entry_id):
    entry = _get_entry_or_404(entry_id)
    engine = get_theme_engine()
    fs_meta = engine.get_theme_meta(entry.slug) or {}

    if request.method == 'POST':
        form = request.form
        # ── Basic fields ──────────────────────────────────────────────────
        name          = (form.get('name') or '').strip()
        description   = (form.get('description') or '').strip()
        category      = (form.get('category') or '').strip()
        theme_author  = (form.get('theme_author') or '').strip()
        theme_version = (form.get('theme_version') or '').strip()
        required_plan = (form.get('required_plan') or '').strip().lower()
        is_premium_raw = form.get('is_premium', 'defer')
        is_active     = form.get('is_active') == 'on'
        is_featured   = form.get('is_featured') == 'on'
        thumbnail_url = (form.get('thumbnail_url') or '').strip()
        banner_url    = (form.get('banner_url') or '').strip()
        thumbnail_url, thumbnail_err = _normalize_theme_media_url(thumbnail_url)
        banner_url, banner_err = _normalize_theme_media_url(banner_url)
        try:
            sort_order = int(form.get('sort_order') or 0)
        except (TypeError, ValueError):
            sort_order = 0

        # Tags: comma-separated
        raw_tags = (form.get('theme_tags') or '').strip()
        tags = [t.strip() for t in raw_tags.split(',') if t.strip()]

        # Feature matrix: one checkbox per feature key
        _FEATURES = ['hero', 'about', 'projects', 'skills', 'services',
                     'testimonials', 'timeline', 'resume', 'contact',
                     'gallery', 'blog', 'shop']
        matrix = {f: (form.get(f'feature_{f}') == 'on') for f in _FEATURES}

        media_errors = [e for e in (thumbnail_err, banner_err) if e]
        if required_plan and required_plan not in VALID_REQUIRED_PLANS:
            flash('Invalid required plan selection.', 'danger')
        elif media_errors:
            for msg in media_errors:
                flash(msg, 'warning')
        else:
            entry.name          = name or None
            entry.description   = description or None
            entry.category      = category or None
            entry.theme_author  = theme_author or None
            entry.theme_version = theme_version or None
            entry.required_plan = required_plan or None
            entry.is_active     = is_active
            entry.is_featured   = is_featured
            entry.sort_order    = sort_order
            entry.thumbnail_url = thumbnail_url
            entry.banner_url = banner_url
            entry.set_tags(tags)
            entry.set_feature_matrix(matrix)
            if is_premium_raw == 'defer':
                entry.is_premium = None
            else:
                entry.is_premium = (is_premium_raw == 'true')

            try:
                db.session.commit()
            except Exception as exc:
                db.session.rollback()
                logger.exception('Failed to update theme catalog entry %s: %s', entry.slug, exc)
                flash('Database error while saving. Please try again.', 'danger')
                return render_template(
                    'superadmin/theme_form.html', entry=entry, fs_meta=fs_meta,
                    page_title=f'Edit Theme — {entry.slug}',
                )
            engine.clear_cache()
            log_activity('update', 'theme_catalog', entry.slug, f'Updated theme catalog entry "{entry.slug}"')
            flash(f'Theme "{entry.slug}" updated successfully.', 'success')
            return redirect(url_for('superadmin.theme_catalog'))

    return render_template(
        'superadmin/theme_form.html', entry=entry, fs_meta=fs_meta,
        page_title=f'Edit Theme — {entry.slug}',
    )


# ── Image upload endpoints ────────────────────────────────────────────────────

@superadmin.route('/themes/<int:entry_id>/upload-thumbnail', methods=['POST'])
@superadmin_required
@limiter.limit('20 per minute')
def theme_upload_thumbnail(entry_id):
    entry = _get_entry_or_404(entry_id)
    f = request.files.get('thumbnail')
    if not f:
        return jsonify({'ok': False, 'message': 'No file uploaded.'})
    if not _allowed_image(f.filename):
        return jsonify({'ok': False, 'message': 'Allowed types: PNG, JPG, JPEG, WEBP, GIF'})
    url = _save_uploaded_image(f, f'thumb_{entry.slug}')
    if not url:
        return jsonify({'ok': False, 'message': 'Upload failed — file too large or invalid.'})
    entry.thumbnail_url = url
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to save thumbnail for %s: %s', entry.slug, exc)
        return jsonify({'ok': False, 'message': 'Database error saving thumbnail.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True, 'url': url})




@superadmin.route('/themes/<int:entry_id>/clear-thumbnail', methods=['POST'])
@superadmin_required
@limiter.limit('30 per minute')
def theme_clear_thumbnail(entry_id):
    entry = _get_entry_or_404(entry_id)
    old_url = entry.thumbnail_url
    entry.thumbnail_url = None
    if old_url:
        from app.utils import delete_image
        delete_image(old_url, 'themes')
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to clear thumbnail for %s: %s', entry.slug, exc)
        return jsonify({'ok': False, 'message': 'Database error clearing thumbnail.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True})


@superadmin.route('/themes/<int:entry_id>/upload-banner', methods=['POST'])
@superadmin_required
@limiter.limit('20 per minute')
def theme_upload_banner(entry_id):
    entry = _get_entry_or_404(entry_id)
    f = request.files.get('banner')
    if not f:
        return jsonify({'ok': False, 'message': 'No file uploaded.'})
    if not _allowed_image(f.filename):
        return jsonify({'ok': False, 'message': 'Allowed types: PNG, JPG, JPEG, WEBP, GIF'})
    url = _save_uploaded_image(f, f'banner_{entry.slug}')
    if not url:
        return jsonify({'ok': False, 'message': 'Upload failed — file too large or invalid.'})
    entry.banner_url = url
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to save banner for %s: %s', entry.slug, exc)
        return jsonify({'ok': False, 'message': 'Database error saving banner.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True, 'url': url})


@superadmin.route('/themes/<int:entry_id>/clear-banner', methods=['POST'])
@superadmin_required
@limiter.limit('30 per minute')
def theme_clear_banner(entry_id):
    entry = _get_entry_or_404(entry_id)
    old_url = entry.banner_url
    entry.banner_url = None
    if old_url:
        from app.utils import delete_image
        delete_image(old_url, 'themes')
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to clear banner for %s: %s', entry.slug, exc)
        return jsonify({'ok': False, 'message': 'Database error clearing banner.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True})


@superadmin.route('/themes/<int:entry_id>/upload-preview', methods=['POST'])
@superadmin_required
@limiter.limit('20 per minute')
def theme_upload_preview(entry_id):
    entry = _get_entry_or_404(entry_id)
    existing = entry.get_preview_images()
    if len(existing) >= _MAX_PREVIEWS:
        return jsonify({'ok': False, 'message': f'Maximum {_MAX_PREVIEWS} preview images allowed.'})
    f = request.files.get('preview')
    if not f:
        return jsonify({'ok': False, 'message': 'No file uploaded.'})
    if not _allowed_image(f.filename):
        return jsonify({'ok': False, 'message': 'Allowed types: PNG, JPG, JPEG, WEBP, GIF'})
    url = _save_uploaded_image(f, f'prev_{entry.slug}')
    if not url:
        return jsonify({'ok': False, 'message': 'Upload failed — file too large or invalid.'})
    existing.append(url)
    entry.set_preview_images(existing)
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to save preview for %s: %s', entry.slug, exc)
        return jsonify({'ok': False, 'message': 'Database error saving preview image.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True, 'url': url, 'previews': existing})


@superadmin.route('/themes/<int:entry_id>/delete-preview', methods=['POST'])
@superadmin_required
@limiter.limit('30 per minute')
def theme_delete_preview(entry_id):
    entry = _get_entry_or_404(entry_id)
    url_to_remove = (request.form.get('url') or '').strip()
    existing = [u for u in entry.get_preview_images() if u != url_to_remove]
    entry.set_preview_images(existing)
    if url_to_remove:
        from app.utils import delete_image
        delete_image(url_to_remove, 'themes')
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to delete preview for entry_id=%s: %s', entry_id, exc)
        return jsonify({'ok': False, 'message': 'Database error removing preview.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True, 'previews': existing})


# ── Toggle active ─────────────────────────────────────────────────────────────

@superadmin.route('/themes/<int:entry_id>/toggle-active', methods=['POST'])
@superadmin_required
def theme_catalog_toggle_active(entry_id):
    entry = _get_entry_or_404(entry_id)
    entry.is_active = not entry.is_active
    status = 'activated' if entry.is_active else 'deactivated'
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to toggle theme %s: %s', entry.slug, exc)
        flash('Unable to update theme status.', 'danger')
        return redirect(url_for('superadmin.theme_catalog'))
    get_theme_engine().clear_cache()
    log_activity('update', 'theme_catalog', entry.slug, f'Theme "{entry.slug}" {status}')
    flash(f'Theme "{entry.slug}" has been {status}.', 'success')
    return redirect(url_for('superadmin.theme_catalog'))


# ── Toggle featured ───────────────────────────────────────────────────────────

@superadmin.route('/themes/<int:entry_id>/toggle-featured', methods=['POST'])
@superadmin_required
def theme_catalog_toggle_featured(entry_id):
    entry = _get_entry_or_404(entry_id)
    try:
        entry.is_featured = not entry.is_featured
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to toggle featured for entry_id=%s: %s', entry_id, exc)
        return jsonify({'ok': False, 'message': 'Database error updating featured status.'})
    get_theme_engine().clear_cache()
    return jsonify({'ok': True, 'is_featured': entry.is_featured})


# ── Delete catalog row ────────────────────────────────────────────────────────

@superadmin.route('/themes/<int:entry_id>/delete', methods=['POST'])
@superadmin_required
@limiter.limit('30 per minute')
def theme_catalog_delete(entry_id):
    entry = _get_entry_or_404(entry_id)
    slug = entry.slug
    db.session.delete(entry)
    try:
        db.session.commit()
    except Exception as exc:
        db.session.rollback()
        logger.exception('Failed to delete theme catalog entry %s: %s', slug, exc)
        flash('Unable to delete catalog override.', 'danger')
        return redirect(url_for('superadmin.theme_catalog'))
    get_theme_engine().clear_cache()
    log_activity('delete', 'theme_catalog', slug,
                 f'Removed catalog override for theme "{slug}" (reverted to theme.json defaults)')
    flash(f'Catalog override removed for "{slug}" — it now uses its theme.json defaults.', 'success')
    return redirect(url_for('superadmin.theme_catalog'))